<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTcNIt3p\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTcNIt3p/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTcNIt3p.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTcNIt3p\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTcNIt3p\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TcNIt3p',
    'container.build_id' => 'b5c2d248',
    'container.build_time' => 1613272800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTcNIt3p');
